title: Selenea Gibson
logo: FB_IMG_1576896010518
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
Previously I was attending Howard Community College and graduated with a Asociates degree in CAD. I then decided to further my career and go for my BA.
  Second description 
  <br>  I am currently a senior at UMBC and will be pursuing my master's in the Fall of 2021. I love Geography and Landscapes, so traveling is my go-to.
<br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
