title: Selenea Gibson
logo: "Sgibson64.github.io/78090573.jfif"
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
**About Me**
  <br>Previously I was attending Howard Community College and graduated with a Associates degree in CAD. I then decided to further my career and go for my BA.   
  I am currently a senior at UMBC and will be pursuing my master's in the Fall of 2021. I love Geography and Landscapes, so traveling is my go-to.<br>
  <br>
**Future Life**
  <br>I am hoping to pursue my dream of working in the field of Critical Nature and helping to restablish animal species. Wanting to become Sustainable 
   for the environment is another goal of mine.<br>  
   
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
