title: Selenea Gibson
logo: "Sgibson64.github.io/78090573.jfif"
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
   <strong>About Me</strong>
  <br>Previously I was attending Howard Community College and graduated with a Associates degree in CADD. I then decided to further my career and go for my BA. 
  I am studying Geography and Environmental Studies with a minor in American Studies.     
  I am currently a senior at UMBC and will be pursuing my master's in the Fall of 2021. I love Geography and Landscapes, so traveling is my go-to after my school career is done.<br>
  <br>
   <strong>Future Life</strong>
  <br>I am hoping to pursue my dream of working in the field of Department of Natrual Resources or a large organization that helps to restablish animal species. Wanting to become Sustainable for the 
   for the environment is another goal of mine.<br>  
   
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
